// Objective 1 NER layer. Uses a real transformer food/recipe NER model through Hugging Face Inference Providers.
// ReciFine RecipeBERT is a BERT-base token-classification model trained for recipe-focused NER.
const TYPES=new Set(['INGREDIENT','ALLERGEN','NUTRIENT','QUANTITY','UNIT','DISH']);
const DEFAULT_MODEL='nuhuibrahim/recifinegold-recipebert-trad';
export function normalizeMenuText(text=''){return String(text).replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim()}
export function normalizeEntities(entities=[]){return entities.filter(e=>e&&TYPES.has(String(e.type).toUpperCase())&&e.text).map(e=>({text:String(e.text).trim(),type:String(e.type).toUpperCase(),start:Number.isFinite(e.start)?e.start:null,end:Number.isFinite(e.end)?e.end:null,confidence:Number.isFinite(e.confidence)?e.confidence:null}));}
export function toStructuredExtraction(entities=[]){const out={ingredients:[],allergens:[],nutrition:[],quantities:[],units:[],dishes:[]};for(const e of normalizeEntities(entities)){const k={INGREDIENT:'ingredients',ALLERGEN:'allergens',NUTRIENT:'nutrition',QUANTITY:'quantities',UNIT:'units',DISH:'dishes'}[e.type];if(k&&!out[k].some(x=>x.text.toLowerCase()===e.text.toLowerCase()))out[k].push(e)}return out}
function mapHFEntity(e){const label=String(e.entity_group||e.entity||'').toUpperCase().replace(/^B-|^I-/,'');const type=label==='FOOD'?'INGREDIENT':label==='QUANTITY'?'QUANTITY':label==='FOOD_STATE'?'DISH':null;if(!type)return null;return{text:e.word||e.text,type,start:e.start,end:e.end,confidence:Number.isFinite(e.score)?e.score:null}}
export async function parseWithTransformer(text,{endpoint,token,model=process.env.NER_MODEL||DEFAULT_MODEL}={}){const clean=normalizeMenuText(text);if(!clean)throw new Error('Menu text is empty');const hfToken=token||process.env.HF_TOKEN;if(endpoint){const res=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({text:clean,task:'food-ner',entity_types:[...TYPES]})});if(!res.ok)throw new Error(`NER transformer returned ${res.status}`);const data=await res.json();return toStructuredExtraction(data.entities||data.predictions||[])}if(!hfToken)throw new Error('HF_TOKEN is not configured. Add a Hugging Face token with Inference Providers permission in Vercel.');const url=`https://router.huggingface.co/hf-inference/models/${model}`;const res=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${hfToken}`,'Content-Type':'application/json'},body:JSON.stringify({inputs:clean,parameters:{aggregation_strategy:'simple'}})});if(!res.ok){const body=await res.text();throw new Error(`Hugging Face NER returned ${res.status}: ${body.slice(0,300)}`)}const data=await res.json();const entities=Array.isArray(data)?data.map(mapHFEntity).filter(Boolean):[];return toStructuredExtraction(entities)}
